version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 132465
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 132465
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  postgres_data:

